### ISSUE TITLE
Structures Dump

### ISSUE THREAD

**Issue by supersaiyansubtlety** [pearxteam/craftdumper#1]
Would it be possible to add dumping of all possible structures that can generate? 
Ideally it would also include some information on the conditions under which they generate, like biome and dimension or something.

**Comment by mrapplexz** [comment]
It's possible to dump all the `IWorldGenerator` class names with their weights, however I can't get any additional information, because mod authors write all the conditions directly in `generate` method. For example, look at the [NetherOreGenerator class](https://github.com/SlimeKnights/TinkersConstruct/blob/23034cb63e98bba06faf1cdc4074009daf93be1f/src/main/java/slimeknights/tconstruct/shared/worldgen/NetherOreGenerator.java#L36-L46) from Tinkers' Construct.

**Comment by supersaiyansubtlety** [comment]
I think just the class names and their weights could be quite useful : )

**Comment by mrapplexz** [comment]
Check out the 1.1.0 update on CurseForge

**Comment by supersaiyansubtlety** [comment]
Awesome, thanks so much!
